db.user: baba
db.password: baba
db.portNo: 5984
db.hostName: localhost
db.name: freelancer

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/freelancer
