spring:
  main:
    allow-circular-references: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/freelancer
    
db.user: baba
db.password: baba
db.portNo: 5984
db.hostName: localhost
db.name: freelancer
