db.user: baba
db.password: baba
db.portNo: 5985
db.hostName: couchdb
db.name: freelancer

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/freelancer
