eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
      
spring:
   cloud:
    gateway:
      routes:
      - id: freelancer
        uri: lb://FREELANCER-API
        predicates:
        - Path=/freelancer/**
