eureka:
  client:
    service-url:
      default-zone: http://EUREKA-SERVER
     
     
spring:

   main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
   cloud:
    gateway:
    
      default-filters:

        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:

        corsConfigurations:

          '[/**]':

              allowedOrigins: "*"

              allowedMethods: "*"

              allowedHeaders: "*"
      routes:
      - id: freelancer-cud-service
        uri: lb://FREELANCER-CUD-API
        predicates:
        - Path=/freelancer-cud-api/**
        
      - id: freelancer-retrieve-service
        uri: lb://FREELANCER-RETRIEVE-API
        predicates:
        - Path=/freelancer-retrieve-api/**
